
import { Patient, Persona } from './types';

export const MOCK_PATIENTS: Patient[] = [
  // DERMATOLOGY PATIENTS
  {
    id: '1',
    name: 'Doe, John',
    dob: '01/01/1960',
    mrn: 'MRN-4829-X',
    referralDate: '2024-05-15',
    department: 'Dermatology',
    urgency: 'Urgent',
    status: 'Triage Pending',
    gpNote: 'Presenting with suspicious lesion on left arm, increasing in size and changing color. Patient reports it is itchy.',
    history: 'Previous melanoma excision 5 years ago. Family history of skin cancer.',
    comorbidities: ['Hypertension', 'Type 2 Diabetes', 'Warfarin (Anticoagulant)'],
    procedure: 'Excision',
    waitingDays: 3,
    clinicType: 'Dermatology Urgent',
  },
  {
    id: '2',
    name: 'Smith, Jane',
    dob: '15/03/1975',
    mrn: 'MRN-9120-A',
    referralDate: '2024-05-18',
    department: 'Dermatology',
    urgency: 'Routine',
    status: 'Intake Review',
    gpNote: 'Recurrent sebaceous cyst on upper back. Requests removal due to discomfort.',
    history: 'General health good. No allergies.',
    comorbidities: [],
    procedure: 'Cyst Removal',
    waitingDays: 1,
    clinicType: 'Dermatology Minor Ops',
  },
  {
    id: '3',
    name: 'Bloggs, Joe',
    dob: '22/11/1982',
    mrn: 'MRN-3341-B',
    referralDate: '2024-05-20',
    department: 'Dermatology',
    urgency: 'Inter Regular',
    status: 'Triage Pending',
    gpNote: 'Atypical mole on torso. Change noted over 6 months.',
    history: 'Smoker, BMI 30.',
    comorbidities: ['Asthma'],
    procedure: 'Biopsy',
    waitingDays: 2,
    clinicType: 'Dermatology Clinic',
  },
  {
    id: '4',
    name: 'Harrison, Sarah',
    dob: '12/08/1955',
    mrn: 'MRN-7723-C',
    referralDate: '2024-05-10',
    department: 'Dermatology',
    urgency: 'Urgent',
    status: 'Awaiting Scheduling',
    gpNote: 'Basal Cell Carcinoma confirmed via biopsy. Needs excision.',
    history: 'Otherwise fit and well.',
    comorbidities: ['Arthritis'],
    procedure: 'BCC Excision',
    waitingDays: 8,
    clinicType: 'Dermatology Urgent',
  },
  {
    id: '5',
    name: 'Patel, Amit',
    dob: '05/05/1990',
    mrn: 'MRN-1029-D',
    referralDate: '2024-05-22',
    department: 'Dermatology',
    urgency: 'Not Set',
    status: 'Intake Review',
    gpNote: 'Large lipoma on shoulder. Affecting range of motion.',
    history: 'No significant past medical history.',
    comorbidities: [],
    waitingDays: 0,
    clinicType: 'Dermatology Minor Ops',
  },
  {
    id: '6',
    name: 'Thompson, Emily',
    dob: '30/12/2002',
    mrn: 'MRN-5561-E',
    referralDate: '2024-05-01',
    department: 'Dermatology',
    urgency: 'Routine',
    status: 'Confirmed',
    gpNote: 'Minor skin tag removal.',
    history: 'Anxiety.',
    comorbidities: [],
    procedure: 'Minor Ops',
    waitingDays: 17,
    clinicType: 'Dermatology Minor Ops',
  },
  {
    id: '7',
    name: 'Williams, Robert',
    dob: '15/09/1968',
    mrn: 'MRN-2156-F',
    referralDate: '2024-05-12',
    department: 'Dermatology',
    urgency: '2WW',
    status: 'Triage Pending',
    gpNote: 'Rapidly growing pigmented lesion on back. ABCDE criteria positive. Urgent 2-week wait referral.',
    history: 'Sun exposure history. Works outdoors. No family history.',
    comorbidities: ['Hypertension'],
    procedure: 'Wide Local Excision',
    waitingDays: 6,
    clinicType: '2WW Dermatology',
  },
  {
    id: '8',
    name: 'Brown, Linda',
    dob: '22/03/1985',
    mrn: 'MRN-7842-G',
    referralDate: '2024-05-19',
    department: 'Dermatology',
    urgency: 'Routine',
    status: 'Awaiting Scheduling',
    gpNote: 'Multiple seborrheic keratoses. Patient requests removal for cosmetic reasons.',
    history: 'Otherwise healthy. No significant medical history.',
    comorbidities: [],
    procedure: 'Cryotherapy',
    waitingDays: 1,
    clinicType: 'Dermatology Clinic',
  },

  // PLASTIC SURGERY PATIENTS
  {
    id: '9',
    name: 'Davies, Michael',
    dob: '10/06/1978',
    mrn: 'MRN-3421-H',
    referralDate: '2024-05-14',
    department: 'Plastic Surgery',
    urgency: 'Urgent',
    status: 'Triage Pending',
    gpNote: 'Partial thickness burn to right hand sustained at work. 15% TBSA. Requires urgent assessment for possible skin grafting.',
    history: 'Occupational injury. Manual worker. Previously fit and well.',
    comorbidities: [],
    procedure: 'Burn Assessment & Grafting',
    waitingDays: 4,
    clinicType: 'Plastic Surgery Burns',
  },
  {
    id: '10',
    name: 'Martinez, Sofia',
    dob: '08/12/1992',
    mrn: 'MRN-5567-I',
    referralDate: '2024-05-16',
    department: 'Plastic Surgery',
    urgency: 'Routine',
    status: 'Intake Review',
    gpNote: 'Post-mastectomy breast reconstruction request. Patient completed cancer treatment 6 months ago.',
    history: 'Breast cancer treated with mastectomy and chemotherapy. Now in remission.',
    comorbidities: ['Breast Cancer (Treated)'],
    procedure: 'Breast Reconstruction',
    waitingDays: 2,
    clinicType: 'Plastic Surgery Reconstruction',
  },
  {
    id: '11',
    name: 'Khan, Ahmed',
    dob: '25/04/1955',
    mrn: 'MRN-8893-J',
    referralDate: '2024-05-11',
    department: 'Plastic Surgery',
    urgency: 'Urgent',
    status: 'Awaiting Scheduling',
    gpNote: 'Traumatic facial laceration following RTC. Complex wound involving upper lip and cheek. Requires urgent plastic surgery review.',
    history: 'Road traffic collision 2 days ago. Otherwise healthy.',
    comorbidities: [],
    procedure: 'Facial Trauma Repair',
    waitingDays: 7,
    clinicType: 'Plastic Surgery Trauma',
  },
  {
    id: '12',
    name: 'O\'Connor, Fiona',
    dob: '18/07/1969',
    mrn: 'MRN-6642-K',
    referralDate: '2024-05-17',
    department: 'Plastic Surgery',
    urgency: 'Routine',
    status: 'Triage Pending',
    gpNote: 'Carpal tunnel syndrome, failed conservative management. Requesting surgical release.',
    history: 'Long-standing symptoms. Conservative management including splinting and steroid injection ineffective.',
    comorbidities: ['Type 2 Diabetes'],
    procedure: 'Carpal Tunnel Release',
    waitingDays: 1,
    clinicType: 'Plastic Surgery Hand',
  },
  {
    id: '13',
    name: 'Wilson, David',
    dob: '05/11/1943',
    mrn: 'MRN-9021-L',
    referralDate: '2024-05-13',
    department: 'Plastic Surgery',
    urgency: 'Inter Regular',
    status: 'Awaiting Scheduling',
    gpNote: 'Dupuytren\'s contracture affecting ring and little finger. Significant functional impairment.',
    history: 'Progressive contracture over 3 years. Family history of Dupuytren\'s.',
    comorbidities: ['Hypertension', 'Osteoarthritis'],
    procedure: 'Dupuytren\'s Fasciectomy',
    waitingDays: 5,
    clinicType: 'Plastic Surgery Hand',
  },
  {
    id: '14',
    name: 'Patel, Priya',
    dob: '14/02/1988',
    mrn: 'MRN-4475-M',
    referralDate: '2024-05-09',
    department: 'Plastic Surgery',
    urgency: 'Routine',
    status: 'Confirmed',
    gpNote: 'Trigger finger (right middle finger). Failed steroid injection. Requesting surgical release.',
    history: 'Occupational therapist. Symptoms affecting work.',
    comorbidities: [],
    procedure: 'Trigger Finger Release',
    waitingDays: 9,
    clinicType: 'Plastic Surgery Hand',
  },
  {
    id: '15',
    name: 'Taylor, James',
    dob: '29/08/1991',
    mrn: 'MRN-7738-N',
    referralDate: '2024-05-21',
    department: 'Plastic Surgery',
    urgency: 'Urgent',
    status: 'Triage Pending',
    gpNote: 'Necrotizing fasciitis suspected - urgent surgical debridement required. Red, swollen, extremely painful lower leg following minor injury.',
    history: 'Presented to A&E with rapidly progressing infection. Septic.',
    comorbidities: ['Type 1 Diabetes'],
    procedure: 'Emergency Debridement',
    waitingDays: 1,
    clinicType: 'Plastic Surgery Emergency',
  },
  {
    id: '16',
    name: 'Anderson, Claire',
    dob: '12/05/1976',
    mrn: 'MRN-1124-O',
    referralDate: '2024-05-08',
    department: 'Plastic Surgery',
    urgency: 'Routine',
    status: 'Scheduled',
    gpNote: 'Hypertrophic scarring post-cesarean section. Patient requests scar revision for cosmetic and functional reasons.',
    history: 'C-section 2 years ago. Keloid tendency. No other surgical history.',
    comorbidities: [],
    procedure: 'Scar Revision',
    waitingDays: 10,
    clinicType: 'Plastic Surgery Reconstruction',
  },
  {
    id: '17',
    name: 'Singh, Rajesh',
    dob: '03/09/1965',
    mrn: 'MRN-8851-P',
    referralDate: '2024-05-15',
    department: 'Plastic Surgery',
    urgency: 'Inter Regular',
    status: 'Intake Review',
    gpNote: 'Ganglion cyst on wrist. Previously drained but recurred. Requesting excision.',
    history: 'Recurrent ganglion. Affecting work as chef.',
    comorbidities: [],
    procedure: 'Ganglion Excision',
    waitingDays: 3,
    clinicType: 'Plastic Surgery Hand',
  },
  {
    id: '18',
    name: 'Murphy, Sean',
    dob: '17/01/1982',
    mrn: 'MRN-3309-Q',
    referralDate: '2024-05-10',
    department: 'Plastic Surgery',
    urgency: '2WW',
    status: 'Awaiting Scheduling',
    gpNote: 'Squamous cell carcinoma on left ear. Biopsy confirmed. Requires wide local excision and possible reconstruction.',
    history: 'Outdoor worker. Significant sun exposure. Biopsy-proven SCC.',
    comorbidities: ['Smoker'],
    procedure: 'SCC Excision + Reconstruction',
    waitingDays: 8,
    clinicType: '2WW Plastic Surgery',
  },
];

export const PERSONA_CONFIG = {
  [Persona.CLINICIAN]: {
    title: 'Clinician / Doctor',
    subtitle: 'The Decision Maker',
    icon: 'Stethoscope',
    description: 'Triage referrals, record outcomes, and review complex patient contexts with AI support.'
  },
  [Persona.WAITING_LIST]: {
    title: 'Waiting List Office',
    subtitle: 'The Orchestrator',
    icon: 'ClipboardList',
    description: 'Digital management of theatre lists and scheduling operations.'
  },
  [Persona.PAC]: {
    title: 'Patients Appointments Centre',
    subtitle: 'The Booking Hub',
    icon: 'Calendar',
    description: 'Book patients into clinics according to urgency and availability.'
  },
  [Persona.MANAGEMENT]: {
    title: 'Management',
    subtitle: 'The Overseer',
    icon: 'BarChart',
    description: 'High-level visibility into backlog volumes, wait times, and operational bottlenecks.'
  }
};
